stages:
  - "Release"

Releasing Docker Image:
  image: docker:latest
  services:
    - docker:dind
  stage: "Release"
  variables:
    DOCKERHUB_IMAGE: "shibme/dockerinspect"
    ECR_PUBLIC_REGISTRY: "public.ecr.aws"
    ECR_PUBLIC_IMAGE: "public.ecr.aws/shibme/dockerinspect"
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - docker logout $CI_REGISTRY
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker tag $CI_REGISTRY_IMAGE $DOCKERHUB_IMAGE
    - docker push $DOCKERHUB_IMAGE
    - docker logout
    - docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY amazon/aws-cli ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_PUBLIC_REGISTRY
    - docker tag $CI_REGISTRY_IMAGE $ECR_PUBLIC_IMAGE
    - docker push $ECR_PUBLIC_IMAGE
    - docker logout $ECR_PUBLIC_REGISTRY
  only:
    - master
