stages:
  - "Build"
  - "Release"

DockerInspect Base Image Build:
  image: docker:latest
  services:
    - docker:dind
  stage: "Build"
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:base .
    - docker push $CI_REGISTRY_IMAGE:base
    - docker logout $CI_REGISTRY
  only:
    - master

Maven Build:
  image: maven:3-jdk-11
  stage: "Build"
  script: mvn -s .m2/settings.xml clean install
  artifacts:
    expire_in: 1 day
    paths:
      - target/dockerinspect-jar-with-dependencies.jar
  only:
    - master

DockerInspect Image Release:
  image: docker:latest
  services:
    - docker:dind
  stage: "Release"
  variables:
    DOCKER_IMAGE: "shibme/dockerinspect"
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - docker logout
  only:
    - master
